### ISSUE TITLE
missing components folder?

### ISSUE THREAD

**Issue by ziponia** [swatisucharita/react-family-tree#1]
Thank you for presenting a good way at https://medium.com/@swatisucharita94/recursive-rendering-in-react-42666102eae2

But it seems there is no components folder inside the project.

Have you ever missed a commit?

**Comment by swatisucharita** [comment]
Usually there is a component folder, but in the repo I have not used one as it's a very small application. All components under src folder only.

**Comment by WendyMartinez** [comment]
Hi.. @ziponia  said this : import FamilyTree from './**components/**familyTree' 

Have you ever missed a commit?

**Comment by swatisucharita** [comment]
I have pushed the missing FamilyTree component. Thanks a lot for letting me know.

**Comment by ziponia** [comment]
@swatisucharita Thank You!

**Comment by swatisucharita** [comment]
Thanks for letting me know. I have pushed the missing components.
